azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 8GiB
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
remote_ci_setup:
  - "conda-forge-ci-setup>=4.9.4"  # make CI helpers new enough to understand "skipped" jobs
github:
  branch_name: main
  tooling_branch_name: main
test: native
