azure:
  free_disk_space: true
  settings_linux:
    # this is somewhat fine-tuned; with a 10GB swapfile, the aarch+CUDA builds run out
    # of disk space, while 5GB is not enough to pass the test suite (esp. on py3.14)
    swapfile_size: 7GiB
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native
